// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	addLibraryFolder: () => typedError<{
	name: string,
	comicFiles: number,
	unreadableFolders: number,
} | null, IpcError>(__TAURI_INVOKE("add_library_folder")),
	matchSystemBars: (theme: Theme, preference: ThemePreference) => typedError<null, IpcError>(__TAURI_INVOKE("match_system_bars", { theme, preference })),
	copyVersionDetails: () => typedError<null, IpcError>(__TAURI_INVOKE("copy_version_details")),
	openProjectLink: (link: ProjectLink) => typedError<null, IpcError>(__TAURI_INVOKE("open_project_link", { link })),
};

/* Types */
export type AppInfo = {
	version: string,
	platform: Platform,
	sourceCode: string,
};

export type FolderSurvey = {
	name: string,
	comicFiles: number,
	unreadableFolders: number,
};

export type IpcError = {
	code: IpcErrorCode,
	message: string,
};

export type IpcErrorCode = "folderPickerUnavailable" | "folderUnreadable" | "clipboardUnavailable" | "browserUnavailable" | "internal";

export type Platform = "android" | "ios" | "macos" | "windows" | "linux";

/**  The project's pages the app opens in the system browser; the interface names one, never a URL. */
export type ProjectLink = "sourceCode" | "newIssue";

export type Theme = "light" | "dark";

export type ThemePreference = "system" | "light" | "dark";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

