// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	addLibraryFolder: () => typedError<{
	name: string,
	comicFiles: number,
	unreadableFolders: number,
} | null, IpcError>(__TAURI_INVOKE("add_library_folder")),
};

/* Types */
export type AppInfo = {
	version: string,
};

export type FolderSurvey = {
	name: string,
	comicFiles: number,
	unreadableFolders: number,
};

export type IpcError = {
	code: IpcErrorCode,
	message: string,
};

export type IpcErrorCode = "folderPickerUnavailable" | "folderUnreadable" | "internal";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

