// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	addLibraryFolder: () => typedError<{
	name: string,
	comicFiles: number,
	unreadableFolders: number,
} | null, IpcError>(__TAURI_INVOKE("add_library_folder")),
	copyVersionDetails: () => typedError<null, IpcError>(__TAURI_INVOKE("copy_version_details")),
	openProjectLink: (link: ProjectLink) => typedError<null, IpcError>(__TAURI_INVOKE("open_project_link", { link })),
	offerSavedCrashReport: () => typedError<{
	details: string,
} | null, IpcError>(__TAURI_INVOKE("offer_saved_crash_report")),
	offerInterfaceErrorReport: (error: InterfaceError) => typedError<CrashReportOffer, IpcError>(__TAURI_INVOKE("offer_interface_error_report", { error })),
	sendCrashReport: () => typedError<null, IpcError>(__TAURI_INVOKE("send_crash_report")),
	copyCrashReport: () => typedError<null, IpcError>(__TAURI_INVOKE("copy_crash_report")),
	declineCrashReport: () => typedError<null, IpcError>(__TAURI_INVOKE("decline_crash_report")),
};

/* Types */
export type AppInfo = {
	version: string,
	platform: Platform,
	sourceCode: string,
};

/**  A crash report as the interface shows it, for the person to read before deciding. */
export type CrashReportOffer = {
	details: string,
};

export type FolderSurvey = {
	name: string,
	comicFiles: number,
	unreadableFolders: number,
};

/**  An error the interface didn't handle, as the webview describes it. */
export type InterfaceError = {
	message: string,
	stack: string | null,
};

export type IpcError = {
	code: IpcErrorCode,
	message: string,
};

export type IpcErrorCode = "folderPickerUnavailable" | "folderUnreadable" | "clipboardUnavailable" | "browserUnavailable" | "noCrashReport" | "crashReportUnavailable" | "internal";

export type Platform = "android" | "ios" | "macos" | "windows" | "linux";

/**  The project's pages the app opens in the system browser; the interface names one, never a URL. */
export type ProjectLink = "sourceCode" | "newIssue";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

