[package]
name = "omnileaf-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rusqlite.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
