[package]
name = "omnileaf-fuzz"
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-only"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4.13"
omnileaf-formats = { path = "../crates/omnileaf-formats" }

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[[bin]]
name = "open_book"
path = "fuzz_targets/open_book.rs"
test = false
doc = false
bench = false

[[bin]]
name = "read_book"
path = "fuzz_targets/read_book.rs"
test = false
doc = false
bench = false

[[bin]]
name = "comic_info"
path = "fuzz_targets/comic_info.rs"
test = false
doc = false
bench = false
