[package]
name = "omnileaf-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "omnileaf_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
e2e = ["dep:tauri-plugin-wdio-webdriver"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
omnileaf-engine.workspace = true
serde.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri.workspace = true
tauri-specta.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
thiserror.workspace = true

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-dialog.workspace = true

[target.'cfg(not(windows))'.dependencies]
tauri-plugin-wdio-webdriver = { workspace = true, optional = true }

[lints]
workspace = true
